### PR TITLE
Fetch upstream

### LINKED ISSUE #9791: fix assign-default-project workflow
### Rasa Open Source version

NA

### Rasa SDK version

_No response_

### Rasa X version

_No response_

### Python version

Other

### What operating system are you using?

Linux

### What happened?

The GitHub Action we used in the workflow seems broken. 

https://github.com/RasaHQ/rasa/actions/workflows/assign-default-project.yml?query=actor%3Arasabot

👆🏻 all passed but issues didn't move to default project board. 

### Command / Request

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by HotThoughts**
Resolves https://github.com/RasaHQ/rasa/issues/9791

### CODE REVIEW

**Comment by HotThoughts** [comment]
@m-vdb the upstream repo changed the default branch from `master` to `main`. Do we want to sync with it?

**Review by m-vdb — APPROVED** [review]
👌🏻

**Comment by m-vdb** [comment]
I've updated the default branch to `main` in this repo, thanks @HotThoughts 🙏🏻

**Comment by HotThoughts** [comment]
Will take a look at why this is failing next week 
https://github.com/RasaHQ/create-or-update-project-card/runs/4103914558?check_suite_focus=true

**Pull request merged**
